name: Trigger Cloudflare Pages Deploy Hook

on:
  push:
    branches:
      - main

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Cloudflare Deploy Hook
        run: curl -d "" ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
