name: Trigger Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trigger Cloudflare Deploy Hook
        run: curl -d "" ${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}
